### ISSUE TITLE
Using CAD with instruction-tuned models

### ISSUE THREAD

**Issue by acDante** [zhichaoxu-shufe/context-aware-decoding-qfs#2]
Hi, I am wondering whether you have used chat template (https://huggingface.co/docs/transformers/en/chat_templating) to build the prompts when running CAD experiments with instruction fine-tuned models. If not, where should I change your codes to make it work for chat templates?

**Comment by zhichaoxu-shufe** [comment]
I didn't use the chat template because the llama / mistral models used are pre-trained language models (not instruction finetuned). 

If you want to apply the chat template it is easier to add to the input data, e.g. this function [here](https://github.com/zhichaoxu-shufe/context-aware-decoding-qfs/blob/768865e059445f5b19a16afb50a6dc3635352cbc/src/utils.py#L172C5-L172C27)

**Comment by acDante** [comment]
Thanks for sharing the pointers! Do I need to change anything during the decoding steps to handle the special tokens added by chat templates?

**Comment by zhichaoxu-shufe** [comment]
I think Llama2-chat / Tulu / Mistral models they do not add special tokens. Instead, the template is just treated as regular text sequence and the model is adapted for the template in SFT. In this case, you don't need to make specific changes.

Please cite my paper as you see fit. Thanks!
